---
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Upgrade all packages
  apt: upgrade=dist

- name: Install basic packages
  apt: >
    pkg={{ item }}
    state=present
  with_items:
    - git
    - curl
    - wget
